# Generated by Django 3.2.2 on 2021-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='News', max_length=255),
        ),
    ]
