# Generated by Django 3.2.4 on 2021-06-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0014_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
