# Generated by Django 3.2.4 on 2021-06-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0015_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
