# Generated by Django 3.2.4 on 2021-06-04 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0024_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
